version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - frontend_network  # Add to the same network as frontend and backend
  backend:
    build:
      context: ./backend
    container_name: wearsphere-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    networks:
      - frontend_network  # Add to the same network as frontend and backend
  frontend:
    build:
      context: ./frontend
    container_name: wearsphere-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    networks:
      - frontend_network  # Add to the same network as frontend and backend
  admin:
    build:
      context: ./admin
    container_name: wearsphere-admin
    ports:
      - "5174:5174"
    env_file:
      - ./admin/.env
    networks:
      - frontend_network  # Add to the same network as frontend and backend

volumes:
  mongo-data:

networks:
  frontend_network:
    driver: bridge
