apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: wearsphere
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dakshsawhneyy/wearsphere-frontend
        ports:
        - containerPort: 5173
        env:
        - name: VITE_BACKEND_URL
          value: "http://13.233.88.144:4000"
        - name: VITE_RAZORPAY_KEY_ID
          value: "your_razorpay_key_id"
